pipeline{
    agent any
    stages{
        stage('build'){
            steps{
                sh 'echo "this is build step"'
            }
        }
        stage('test'){
            steps{
                sh 'echo "this is test step"'
            }
        }
        stage('deploy'){
            steps{
                sh 'echo "this is depoly step"'
            }
        }
    }
}